name: Labeling new issue
on:
  issues:
      types: ['opened']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Renato66/auto-label@v2.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels-synonyms: '{"Suggestion":["could you","maybe","what about"],"Q &amp; A":["maybe","what","when","where","who","why","help"],"Online":["Multiplayer","leaderboards"],"Bug":["broken","not working","error"]}'
          labels-not-allowed: '["Wont Fix","Planned","Help Wanted","Fixed","Duplicate"]'
